# loadtest_tiers.ps1
# Sends WATCH / WARM / HOT tier assignments to DataHub tiers service
# Endpoint: http://127.0.0.1:7000/v1/tiers/service

$baseUrl = "http://127.0.0.1:7000/v1/tiers/service"
$source  = "engineer_panel"   # change to "loadtest" if you want to tag them

# Your symbol lists (from the CSV you pasted)
$watchList = "SFIX,ALIT,LPTH,EIC,SLDP,XYF,PSTL,ANGI,PEBO,DFDV,ENOV,TIPT,VRNT,ARI,XRX,INR,LENZ,PGC,DIN,AAM,MSB,GCI,KODK,EMBC,KLC,AFYA,BMEZ,MTW,NMZ,BGS,BWMX,ARIS,TE,CHCT,OMDA,LE,DFIN,TSSI,PDO,RXT,SBH,TRIN,DLX,AOD,ALGT,MBUU,EFC,OPFI,MTAL,DSGR,NXRT,CMPR,FORD,GAM,REKR,RAPT,HRTG,PLBL,AVAL,UFCS,IMAX,CRD-B,PARR,GPAT,PRCT,ETV,RVT,HDL,UDMY,ETB,CRD-A,CYD,CARS,BLBD,BW,PGNY,AFB,JACK,LDI,SD,FULC,AIRO,AXGN,FBRT,DMLP,XPER,HIVE,STAA,MUJ,UXIN,GAIN,FSCO,ITRN,MUX,MCRI,ABL,MCW,SCHL,GTN,MHN,ADCT,BSVN,CRTO,JELD,GHRS,ROG,HELE,SHCO,BRCB,CCD,PANL,GLIBA,CEPU,ACNB,NPAC,EOLS,OBE,BCRX,FLOC,ATRC,NX,UTZ,WABC,ICHR,CET,NTCT,PHAT,TALO,OSBC,ANAB,EDIT,FEIM,VTOL,DSL,ENR,ASGI,ACVA,NGS,GABC,LZ,FOXF,WVE,BWFG,SLQT,IPCX,LXEO,HIPO,EVV,DV,JANX,BRCC,OTLY,IQ,OXLC,COLL,EEX,IGD,IMXI,OPAL,LYEL,SMC,VBTX,BHVN,EHAB,MFA,MSC,DQ,ZYME,SUPV,BTZ,WOW,TSHA,TFIN,DOLE,GHY,NUS,SLRC,DPG,AMRC,ASM,GPCR,NTB,COUR,PHK,ARCB,CTRI,INMD,NXJ,CBLL,TPB,OBT,VITL,AMCX,BKKT,OPY,CWBC,GOTU,CCSI,LILA,AMWD,GBLI,KSS,PX,RPD,STUB,BCSS-U,HMN,DCOM,CLDX,MPAA,MYE,AMPH,TRML,FLNG,LTC,VTS,HTLD,MTRX,CBK,BLZE,DAO,SKYH,SVM,PLAY,OLMA,HQL,MNRO,RA,LASR,BBSI,STOK,CMRE,NMAX,LAB,BBBY,PDM,TRVI,IIIV,GNE,PBT,VSTM,PDS,LOT,VLGEA,NBTX,GLIBK,DDD,RCUS,AHCO,VRTS,IDT,MYI,UROY,AVNS,OOMA,RWAY,FAX,CGNT,CTEV,CLBK,DX,TTGT,TITN,NMG,AXG,LION,OWLS,TRS,EYPT,CCAP,MBIN,GIII,IRMD,FDP,VSTA,MLKN,UMH,EGBN,CLFD,ALM,AESI,BTBT,SEG,RFI,TIXT,RMR,CNL,NAC,JOUT,ARVN,PROK,UTL,NMAI,HOPE,MATW,EFXT,PMI,BVS,WEAV,HTZ,ASLE,GCBC,HTD,GBX,HBNC,ANNA,DDL,MTUS,WTTR,BTQ,CTO,RBBN,NKTR,ARHS,CLNE,CECO,SB,HBNB,PBPB,CARL,TCBK,RMNI,ARDX,VVX,TASK,NPFD,NRP,NAN,VTLE,JFR,BNED,RDVT,NWN,CRNC,JBSS,LUCK,NPK,FLYX,UFPT,ASG,USA,DMIIU,MASS,EBS,AQST,PAHC,NNDM,ADTN,NVAX,TMCI,VSTS,IMKTA,NFGC,HIO,GIBO,CVGW,HIMX,BTO,BALY,BFST,LADR,KRP,ONIT,PHOE,ECPG,CLCO,MNPR,KOPN,WINA,PMT,BHK,EAD,CVAC,ALX,MODG,ACTG,FDUS,CODI,LZM,TNK,OMER,SANA,SMLR,VACH,MAMA,NVCR,IGR,KRNY,GSBC,ADEA,PERI,NC,PFN,CNXN,MSBI,SES,ATRO,RES,SMA,PRGS,HOND,NXP,NABL,SEPN,MLAB,KRRO,MEG,BCX,SWIM,AMPX,ALTI,PKE,CDNA,THFF,NN,RZLT,SEMR,BCYC,CTLP,CINT,MAZE,YORW,OFG,BDJ,PRTH,FIVN,BFS,SNDA,HOUS,HLF,GBFH,VREX,EH,DAKT,SVRA,ABUS,CRF,USAS,PAR,NCDL,AHG,PLSE,SABR,ATAI,KURA,KW,GEVO,TROX,EVO,ERII,GRDN,FISI,PBFS,SOS,SHLS,FOA,GTY,EFR,NAK,BFK,SKYT,PACS,KARO,SPT,NUVB,GSBD,PXED,USCB,BOE,LND,TUYA,RR,TCPC,ILPT,PCN,BACQ,CYRX,CDLR,QQQX,EVN,SCSC,AMPL,WASH,GRPN,CZNC,GERN,EOS,AZTA,TNGX,ULH,MLNK,CRI,VOYG,HFRO,GLUE,BOW,PNNT,NOA,VALU,MLR,FTK,ZH,LIND,ODP,BCML,MDXG,GPRO,NAT,DGICA,PUMP,RYAM,ORIC,SVV,MTA,GRC,CBRL,IIIN,ECC,THM,RBCAA,BGT,SLSR,MYD,SKWD,TALK,PLUS,ARRY,GLAD,TACH,CASS,MREO,CNDT,EXOD,PRG,YALA,INVX,RBB,CHCO,DSGN,BLE,GDRX,TYG,BHB,NBN,HY,MEC,TIGR,NOAH,KREF,DEFT,LFST,TV,PZZA,POET,RGNX,SIMA,CRSR,FLGT,FUBO,ATEN,DIAX,NEGG,PDT,PFL,TH,BWLP,REAX,PWP,ASIX,DCTH,GSL,AKBA,CAPL,MMI,LKFN,COFS,OPRA,USNA,RIGL,NPCE,LTBR,NPWR,NSSC,OFIX,LZB,MPB,GBAB,ESTA,WS,JAMF,TMP,RDWR,EGY,PKST,ASPI,ZD,TNDM,ESRT,VERI,NRDS".Split(',')

$warmList = "SLDB,EDD,SBSI,NFE,QCRH,NQP,SPMC,CVLG,CGBD,BV,ASC,GGN,FOF,LUNR,FIHL,ADSE,CTS,SCS,WERN,CSR,AMTB,BNC,WLKP,STKL,GDYN,MUA,EXPI,ZUMZ,VTEX,OSPN,SXC,VKQ,PRTA,CENTA,HCKT,CSWC,CRESY,HYLN,AXL,GETY,LILAK,OIS,BJRI,AMN,CPAC,CDRE,BY,GNL,PRAA,KALV,TXG,MAX,EOI,KIO,MLTX,BNTC,WOOF,ORGO,BIT,SMBC,ASA,MSEX,DOMO,CGEM,REPX,SLVM,BYRN,HPF,HSII,MXL,SCL,BFC,MG,LVWR,SERV,HIX,ECO,NWBI,AEVA,NBBK,CIM,MBWM,ODC,HPP,HOV,PGRE,ORBS,CHW,ASPN,PRA,STGW,LXU,UAN,IAS,MGPI,PACB,HSHP,VRDN,INBX,PSNL,IMNM,EVEX,SGML,BGB,RMT,LRMR,PRCH,HFWA,CLDT,VHI,IMOS,VENU,DAVA,TECX,ENGN,CASH,EIM,AAMI,RLJ,TWFG,CLOV,QD,PRO,GFR,XFLT,NAGE,SCM,LX,CRMD,NPB,BME,NFJ,IQI,OPK,IE,STEL,CENT,LGIH,LWLG,CBL,TEN,AVBP,NVEC,PUBM,MUC,HRMY,ARMN,DDI,ARMP,CION,ALT,BBW,FOR,DVS,THH,ARCO,ATUS,BXC,SSYS,NBH,CBNK,NGL,MRC,CCS,ARTNA,GMRE,UMAC,LEG,NBXG,AMAL,COHU,BCAX,CHI,FVRR,GLDD,DJCO,CYH,DSU,KRO,PKOH,FFA,EVT,AIO,KROS,JJSF,CAL,BGR,SNDL,ABCL,PRME,CMPX,MVST,ASIC,HIFS,ICFI,ECVT,CLMB,AMBQ,WRLD,PRSU".Split(',')

$hotList = "NML,XPRO,NEO,MSIF,HROW,NCV,AMBC,KFS,OBK,EDN".Split(',')

function Set-TierBatch {
    param(
        [string[]]$Symbols,
        [string]$Tier
    )

    Write-Host "Setting tier $Tier for $($Symbols.Count) symbols..."

    foreach ($sym in $Symbols) {
        $sym = $sym.Trim()
        if (-not $sym) { continue }

        $body = @{
            symbol = $sym
            tier   = $Tier
            source = $source
        } | ConvertTo-Json

        try {
            $resp = Invoke-RestMethod -Uri $baseUrl -Method POST -ContentType "application/json" -Body $body
            Write-Host "[$Tier] $sym -> $($resp | Out-String)" -ForegroundColor Green
        }
        catch {
            Write-Warning "[$Tier] $sym FAILED: $($_.Exception.Message)"
        }

        # Optional: small delay if you want to avoid hammering it too hard
        # Start-Sleep -Milliseconds 10
    }
}

Set-TierBatch -Symbols $watchList -Tier "WATCH"
Set-TierBatch -Symbols $warmList  -Tier "WARM"
Set-TierBatch -Symbols $hotList   -Tier "HOT"

Write-Host "Done assigning WATCH/WARM/HOT loadtest tiers."
